### ISSUE TITLE
Replace screws on azimuth rotator

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#23]

**Comment by Tyler-Ward** [comment]
Screws replaced with Alan keyed bolts, washers couldn't be removed and so washers will also need purchacing
- [x] acquire M6 split washers

**Comment by Tyler-Ward** [comment]
washers available at from. http://www.screwfix.com/p/split-ring-washers-bzp-m6-pack-of-100/3498g?_requestid=317096 
@mnestis can you approve

**Comment by Tyler-Ward** [comment]
@mnestis approved during the meeting

**Comment by Tyler-Ward** [comment]
These have been purchaced

**Comment by drn05r** [comment]
Hex bolts have had spring washers attached and screwed back into azimuth rotator
