### ISSUE TITLE
Check rotator mounting screws are not rusty

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#24]
- [x] determine if current any of the current screws are rusty
- [x] source replacements
- [x] install replacements

**Comment by Tyler-Ward** [comment]
The nuts on the elevation clamps look a bit rusty, everything else looks good.

http://www.screwfix.com/p/nylon-lock-nuts-a2-stainless-steel-m6-pack-of-100/11082 are a replacement
theses cost £3.78.

@mnestis can you approve

**Comment by mnestis** [comment]
£3.78 + reasonable P+P approved.

**Comment by Tyler-Ward** [comment]
These have been purchaced

**Comment by drn05r** [comment]
Nuts replaced with stainless steel ny-loc nuts and spring washers also added.
