### ISSUE TITLE
Get SUSU to install server rack in the "playroom"

### ISSUE THREAD

**Issue by Tyler-Ward** [SUWS/mast-planning#27]
Assignees: @drn05r and @Tyler-Ward 
Dependencies: 
- [ ] await permission #4 
  Sub Tasks:
- [ ] Source the rack so we know exact dimensions and wall mounting options.
- [ ] purchase the rack and mounting hardware
- [ ] arrange installation with susu

**Comment by Tyler-Ward** [comment]
http://www.comms-express.com/products/21u-600mm-deep-data-cabinet-data-rack/ was the rack previously suggested to susu

**Comment by nsefan** [comment]
The playroom has been temporarily closed, and will be reopened in what is currently break-out room 2 on the ground floor. The former playroom has been converted into an office. Need to discuss at length with SUSU to determine exact location of internal radio equipment.

**Comment by Tyler-Ward** [comment]
More info on room move in #44

**Comment by Tyler-Ward** [comment]
The room for the control kit has changed and installation will be carried out in a new location when a room has been decided. see #44 for more info.
